# Generated by Django 2.1.5 on 2019-02-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mymovies.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=100)),
                ('Year', models.CharField(max_length=4)),
                ('Rated', models.CharField(max_length=15)),
                ('Released', models.TextField(max_length=20)),
                ('Runtime', models.TextField(max_length=20)),
                ('Genre', models.TextField(max_length=100)),
                ('Director', models.TextField(max_length=200)),
                ('Actors', models.TextField(max_length=500)),
                ('Plot', models.TextField(max_length=700)),
                ('Language', models.TextField(max_length=50)),
                ('Country', models.TextField(max_length=50)),
                ('Awards', models.TextField(max_length=100)),
                ('Poster', models.TextField(max_length=150)),
                ('rottenRating', models.TextField(max_length=20)),
                ('imdbRating', models.TextField(max_length=10)),
                ('criticRating', models.TextField(max_length=10)),
                ('imdbID', models.CharField(max_length=30)),
                ('Type', models.TextField(max_length=50)),
                ('DVD', models.TextField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='categorymovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mymovies.Movie'),
        ),
    ]
